addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.3")
addSbtPlugin("org.scala-js"     % "sbt-scalajs" % "0.6.20")
addSbtPlugin("com.vmunier" % "sbt-web-scalajs" % "1.0.6")
addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.8.0")

//addSbtPlugin("org.scala-native" % "sbt-crossproject" % "0.2.2")  // (1)
//addSbtPlugin("org.scala-native" % "sbt-scalajs-crossproject" % "0.2.2")  // (2)
//addSbtPlugin("org.scala-native" % "sbt-scala-native"         % "0.3.3")  // (3)
